/*
 * Copyright 2007-2008 Michele Mostarda ( michele.mostarda@gmail.com ).
 * All Rights Reserved.
 * <p/>
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p/>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p/>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.asemantics.model.ontology;

import java.net.URL;
import java.io.OutputStream;
import java.io.PrintStream;

/**
 * Defines the ontology generated by a {@link com.asemantics.model.CodeHandler}
 */
public interface Ontology {

    /**
     * Defines a relation <i>Subject</i>, <i>predicate</i>,
     * <i>object</i> to the ontology.
     *
     * @param subjectPrefix
     * @param predicate
     * @param objectPrefix
     */
    void defineRelation(String subjectPrefix, URL predicate, String objectPrefix) throws OntologyException;

    /**
     * Defines a relation <i>Subject</i>, <i>predicate</i>,
     * <i>literal object</i> to the ontology.
     *
     * @param subjectPrefix
     * @param predicate
     */
    void defineRelation(String subjectPrefix, URL predicate) throws OntologyException;

    /**
     * Removes an already defined relation from the ontology.
     *
     * @param subjectPrefix
     * @param predicate
     * @param objectPrefix
     */
    void undefineRelation(String subjectPrefix, URL predicate, String objectPrefix) throws OntologyException;

    /**
     *  Removes an already defined relation from the ontology.
     *
     * @param subjectPrefix
     * @param predicate
     */
    void undefineRelation(String subjectPrefix, URL predicate) throws OntologyException;

    /**
     * Validates a triple over the current ontology.
     *
     * @param subject 
     * @param predicate 
     * @param object 
     */
    void validateTriple(String subject, String predicate, String object) throws OntologyException;

    /**
     * Validates a triple literal over the current ontology.
     *
     * @param subject
     * @param predicate
     */
    void validateTripleLiteral(String subject, String predicate) throws OntologyException;

    /**
     * Returns the number of relations defined in the ontology.
     *
     * @return
     */
    int getRelationsCount();

    /**
     * Returns <code>true</code> if the i-th <i>object</i> is a literal,
     * <code>false</code> otherwise.
     * 
     * @param i
     * @return
     */
    boolean isLiteralRelation(int i);

    /**
     * Returns the relation i-th subject prefix.
     *
     * @param i
     * @return
     */
    String getRelationSubjectPrefix(int i);

     /**
     * Returns the relation i-th predicate.
      *
     * @param i
     * @return
     */
    URL getRelationPredicate(int i);

    /**
     * Returns the relation i-th object prefix.
     *
     * @param i
     * @return
     */
    String getRelationObjectPrefix(int i);

    /**
     * Prints the current ontology in a readable form.
     *
     * @param ps
     */
    void printOntology(PrintStream ps);

    /**
     * Prints the current ontology in OWL format.
     *
     * @param os
     */
    void toOWL(OutputStream os);

}
